[package]
name = "aufgabe2_fahrstuhl"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
rand = "0.10.0-rc.5"
tokio = { version = "1.48.0", features = ["full"] }
rumqttc = "0.24"
serde_json = "1.0"